### ISSUE TITLE
this is not anonymous

### ISSUE THREAD

**Issue by 89z** [kaex/insta-story#3]
> Download Chrome extension cookies.txt 🍪

> Go to Instagram and login to your account , click on the cookie extension top right corner copy it inside cookie.txt

thats the exact opposite of anonymous, as cookies can be used to uniquely identify a user.

**Comment by kaex** [comment]
You are using the cookie to access instagram endpoint. While you view/download the image or video there is no seen sent so it is anonymous, please make your research better.

**Comment by 89z** [comment]
OK then, tell me how you get cookies without logging in?

Make YOUR research better, homie.

**Comment by kaex** [comment]
@89z Are you joking or you genuinely have no idea how instagram API works? You can't access instagram endpoints if you are not logged in. You need the cookie to crawl in the API and get the image/video to view and download. crawling the API won't trigger the `/seen` endpoint. So you will be fully **anonymous** while viewing/downloading the story.

**Comment by 89z** [comment]
I think you misunderstand what anonymous means. Anonymous means **no authentication**. It means no cookies, no session, no OAuth no nothing. This package might be "anonymous" in terms of other Instagram users, but its not anonymous in terms of the actual HTTPS requests.

**Comment by kaex** [comment]
I have never claimed it is anonymous on **HTTPS** requests?

> This will allow you to see and download anyone (public profile) account stories without getting in the seen list.

**Comment by 89z** [comment]
> About
>
> 🤖 📷 Instagram Story Downloader Anonymously - PHP 

https://github.com/kaex/insta-story

**Comment by kaex** [comment]
The **Anonymously** word used there is:
> This will allow you to see and download anyone (public profile) account stories without getting in the seen list.

You viewing a story without being on the seen list is being **anonymous**.

**Comment by kaex** [comment]
@89z What a weirdo. Removing the comments when you can't win an argument. Good job. I hope you at least understood what **anonymous** means!
